// src/components/TodoItem.svelte
<script>
  import { taskStore } from '../stores/taskStore.js';
  export let task;

  function changePriority() {
    task.priority = task.priority === 'yes' ? 'no' : 'yes';
    taskStore.update(tasks => tasks);
  }

  function removeTask() {
    taskStore.update(tasks => tasks.filter(t => t.id !== task.id));
  }
</script>

<li>
  <button on:click={changePriority} class="priority-button">
    <span class:priority={task.priority === 'yes'}>★</span>
  </button>
  <input type="checkbox" bind:checked={task.checked} />
  <div class="task-content">
    <div class="task-label">
      <label>{task.label}</label>
    </div>
    <div class="task-details">
      <p>{task.category}</p>
      <span>{task.date}, {task.time}</span>
    </div>
  </div>
  <button on:click={removeTask} class="remove-button">X</button>
</li>

<style>
  li {
    display: flex;
    align-items: center;
    margin-bottom: 8px;
    background-color: #1e1e1e;
    border: 1px solid #333;
    padding: 10px;
    border-radius: 8px;
  }

  .priority-button {
    border: none;
    background: none;
    cursor: pointer;
    margin-left: -4px;
  }

  .priority {
    color: gold;
  }

  span:not(.priority) {
    color: rgba(255, 215, 0, 0.3);
  }

  input[type="checkbox"] {
    margin-right: 10px;
    accent-color: #bb86fc;
  }

  .task-content {
    flex-grow: 1;
  }

  .task-label {
    display: flex;
    align-items: center;
  }

  .task-details {
    display: flex;
    justify-content: space-between;
    align-items: center;
  }

  p, span {
    color: #5f6368;
    font-size: 12px;
    margin: 0;
  }

  .remove-button {
    color: red;
    border: none;
    background: none;
    font-size: 15px;
    cursor: pointer;
    margin-left: 15px;
  }
</style>

// components/TodoItem.tsx
"use client"

import { useTaskStore } from '../stores/taskStore'

export default function TodoItem({ task }) {
  const { updateTask, removeTask } = useTaskStore()

  const togglePriority = () => {
    updateTask(task.id, { priority: task.priority === 'yes' ? 'no' : 'yes' })
  }

  return (
    <li className="flex items-center bg-gray-800 p-4 rounded-lg">
      <button onClick={togglePriority} className="mr-2">
        <span className={`text-2xl ${task.priority === 'yes' ? 'text-yellow-400' : 'text-gray-500'}`}>
          ★
        </span>
      </button>
      <input
        type="checkbox"
        checked={task.checked}
        onChange={() => updateTask(task.id, { checked: !task.checked })}
        className="mr-4 h-5 w-5 accent-purple-600"
      />
      <div className="flex-grow">
        <div className="flex items-center">
          <label className={`${task.checked ? 'line-through text-gray-500' : ''}`}>{task.label}</label>
        </div>
        <div className="flex justify-between text-sm text-gray-400 mt-1">
          <span>{task.category}</span>
          <span>{task.date}, {task.time}</span>
        </div>
      </div>
      <button onClick={() => removeTask(task.id)} className="ml-4 text-red-500 hover:text-red-700">
        X
      </button>
    </li>
  )
}
