// app/page.tsx
"use client"

import TodoList from '../components/TodoList'
import TaskCounter from '../components/TaskCounter'
import AddTaskButton from '../components/AddTaskButton'
import RemoveCompletedButton from '../components/RemoveCompletedButton'

export default function Home() {
  return (
    <main className="min-h-screen bg-gray-900 text-white p-8">
      <div className="max-w-2xl mx-auto">
        <h1 className="text-3xl font-bold text-center mb-8">To-do List</h1>
        
        <TodoList />
        
        <hr className="my-8 border-gray-700" />
        
        <TaskCounter />
        
        <div className="flex gap-4 mt-8">
          <AddTaskButton />
          <RemoveCompletedButton />
        </div>
      </div>
    </main>
  )
}

// src/App.svelte
<script>
  import TodoList from './components/TodoList.svelte';
  import TaskCounter from './components/TaskCounter.svelte';
  import AddTaskButton from './components/AddTaskButton.svelte';
  import RemoveCompletedButton from './components/RemoveCompletedButton.svelte';
</script>

<main>
  <h1>To-do List</h1>
  
  <TodoList />
  
  <hr>
  
  <TaskCounter />
  
  <div class="button-container">
    <AddTaskButton />
    <RemoveCompletedButton />
  </div>
</main>

<style>
  :global(body) {
    background-color: #121212;
    color: #FFFFFF;
    font-family: Arial, sans-serif;
    margin: 0;
    padding: 20px;
    box-sizing: border-box;
  }

  main {
    max-width: 600px;
    margin: 0 auto;
  }

  h1 {
    text-align: center;
  }

  hr {
    border-color: #333;
  }

  .button-container {
    display: flex;
    gap: 10px;
    margin-top: 20px;
  }
</style>
